baseURL = "/collectiveDAO"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "github.com/themefisher/twenty-twenty-hugo"
title = "collectiveDAO"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
name = "vote"
url = "https://snapshot.org/#/compusophy.eth"
weight = 2
[[menu.desktop]]
URL = "contact"
name = "vault"
url = "https://opensea.io/0xaae6e2a2d10cfe076937a0858fd202684fa8460a"
weight = 1
[[menu.main]]
name = "vote"
url = "https://snapshot.org/#/compusophy.eth"
weight = 2
[[menu.main]]
name = "vault"
url = "https://opensea.io/0xaae6e2a2d10cfe076937a0858fd202684fa8460ahttps://opensea.io/0xaae6e2a2d10cfe076937a0858fd202684fa8460a"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Themefisher"
description = "This is meta description"
[params.banner]
heading = ""
image = ""
[params.blog]
heading = ""
[params.call_to_action]
button_label = "Contact Us"
button_url = "contact"
content = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
enable = false
title = "Contact us for more information."
[params.footer]
address = ""
content = ""
copyright = "collectiveDAO © 2021"
hours = ""
title = ""
[params.gallery]
enable = false
gallery_item = []
[params.social]
email = ""
facebook = ""
instagram = ""
linkedin = ""
twitter = "https://twitter.com/collectivedao"
yelp = ""
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
